---
title: "Compressive Strength Project - R code"
output: rmarkdown::github_document
  pdf_document: default
  html_notebook: default
---

```{r}
library(readxl)
library(olsrr)
data <- read_excel("Concrete_Data.xls")
names(data) <- c("cement", "blast_furnace_slag","fly_ash","water","superplasticizer","coarse_aggregate","fine_aggregate","age","concrete_compressive_strength")
```


```{r}
# Load necessary libraries
library(ggplot2)
library(ggpubr)

#Plot the response variable vs each explanatory variable 
p1 <- ggplot(data, aes(x = cement, y = concrete_compressive_strength)) + 
  geom_point(size = 1, color = "blue") +
  theme_minimal() + 
  labs(x = "Cement", y = "Concrete Compressive Strength ")

p2 <- ggplot(data, aes(x = blast_furnace_slag, y = concrete_compressive_strength)) + 
  geom_point(size = 1, color = "green") +
  theme_minimal() +
  labs(x = "Blast Furnace Slag", y = "Concrete Compressive Strength ")

p3 <- ggplot(data, aes(x = fly_ash, y = concrete_compressive_strength)) + 
  geom_point(size = 1, color = "red") +
  theme_minimal() + 
  labs(x = "Fly Ash", y = "Concrete Compressive Strength ")

p4 <- ggplot(data, aes(x = water, y = concrete_compressive_strength)) + 
  geom_point(size = 1, color = "purple") +
  theme_minimal() + 
  labs(x = "Water", y = "Concrete Compressive Strength ")

p5 <- ggplot(data, aes(x = superplasticizer, y = concrete_compressive_strength)) + 
  geom_point(size = 1, color = "orange") +
  theme_minimal() + 
  labs(x = "Superplasticizer", y = "Concrete Compressive Strength ")

p6 <- ggplot(data, aes(x = coarse_aggregate, y = concrete_compressive_strength)) + 
  geom_point(size = 1, color = "yellow") +
  theme_minimal() +
  labs(x = "Coarse Aggregate", y = "Concrete Compressive Strength ")

p7 <- ggplot(data, aes(x = fine_aggregate, y = concrete_compressive_strength)) + 
  geom_point(size = 1, color = "lightblue") +
  theme_minimal() + 
  labs(x = "Fine Aggregate", y = "Concrete Compressive Strength ")

p8 <- ggplot(data, aes(x = age, y = concrete_compressive_strength)) + 
  geom_point(size = 1, color = "black") +
  theme_minimal() + 
  labs(x = "Age", y = "Concrete Compressive Strength ")

figure <- ggarrange(p1, p2, p3, p4, p5,p6, p7, p8,
                    labels = c("A", "B", "C","D","E","F","G","H"),
                    ncol = 3, nrow = 3)

#ggsave("plots.png", figure, width = 12, height = 12, units = "in", dpi = 300)
figure

```

```{r}
#Find the correlation between the response variable vs each explanatory variable 
cor_cement <- cor(data$concrete_compressive_strength, data$cement)
cor_bfs <- cor(data$concrete_compressive_strength, data$blast_furnace_slag)
cor_fa <- cor(data$concrete_compressive_strength, data$fly_ash)
cor_water <- cor(data$concrete_compressive_strength, data$water)
cor_sp <- cor(data$concrete_compressive_strength, data$superplasticizer)
cor_ca <- cor(data$concrete_compressive_strength, data$coarse_aggregate)
cor_fa <- cor(data$concrete_compressive_strength, data$fine_aggregate)
cor_age <- cor(data$concrete_compressive_strength, data$age)

print(paste("Correlation between drinks and cement:", cor_cement))
print(paste("Correlation between drinks and bfs:", cor_bfs))
print(paste("Correlation between drinks and fa:", cor_fa))
print(paste("Correlation between drinks and water:", cor_water))
print(paste("Correlation between drinks and sp:", cor_sp))
print(paste("Correlation between drinks and ca:", cor_ca))
print(paste("Correlation between drinks and fa:", cor_fa))
print(paste("Correlation between drinks and age:", cor_age))
```

 
```{r}
#Full Linear Model
model_full_linear <- lm(concrete_compressive_strength~.,data=data)
print(BIC(model_full_linear))
summary(model_full_linear)
```
```{r}
#Residual plot of full linear model
residuals_data <- data.frame(
  Residuals = residuals(model_full_linear),
  Fitted = fitted(model_full_linear)
)

residual_plot_full_linear <- ggplot(residuals_data, aes(x=Fitted, y=Residuals)) +
  geom_point(colour="blue") +
  geom_hline(yintercept=0, colour="red") +
  labs(
    x="Fitted Values",
    y="Residuals"
  ) +
  theme_minimal()

# Print the plot
print(residual_plot_full_linear)
#ggsave("residual_plot_full_linear.png", plot=residual_plot_full_linear, width=10, height=8, dpi=300)
```

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.


```{r}
#Best subset selection
library(leaps)
subset_model <- regsubsets(concrete_compressive_strength~., data = data)
subset_summary <- summary(subset_model)
subset_summary
```
```{r}
#Find adjusted R^2, Cp, and BIC of each model
BIC_1 <- BIC(lm(concrete_compressive_strength~cement, data = data))
BIC_2 <- BIC(lm(concrete_compressive_strength~cement+superplasticizer, data = data))
BIC_3 <- BIC(lm(concrete_compressive_strength~cement+superplasticizer+age, data = data))
BIC_4 <- BIC(lm(concrete_compressive_strength~cement+blast_furnace_slag+water+age, data = data))
BIC_5 <- BIC(lm(concrete_compressive_strength~cement+blast_furnace_slag+fly_ash+water+age, data = data))
BIC_6 <- BIC(lm(concrete_compressive_strength~cement+blast_furnace_slag+fly_ash+water+superplasticizer+age, data = data))
BIC_7 <- BIC(lm(concrete_compressive_strength~cement+blast_furnace_slag+fly_ash+water+superplasticizer+fine_aggregate+age, data = data))
BIC_8 <- BIC(model_full_linear)
data.frame(
  Adj.R2 = subset_summary$adjr2,
  CP = subset_summary$cp,
  BIC = c(BIC_1,BIC_2,BIC_3,BIC_4,BIC_5,BIC_6,BIC_7,BIC_8)
)
```

```{r}
#Model with polynomial terms
model_poly <- lm(concrete_compressive_strength ~ cement + blast_furnace_slag + fly_ash + water + poly(superplasticizer,2) + coarse_aggregate + fine_aggregate + poly(age,2), data = data)
print(BIC(model_poly))
print(ols_mallows_cp(model_poly,model_full_linear))
summary(model_poly)
anova(model_poly)
```
```{r}
#Residual plot of polynomial model
residuals_data <- data.frame(
  Residuals = residuals(model_poly),
  Fitted = fitted(model_poly)
)


residual_plot_poly <- ggplot(residuals_data, aes(x=Fitted, y=Residuals)) +
  geom_point(colour="purple") +
  geom_hline(yintercept=0, colour="red") +
  labs(
    x="Fitted Values",
    y="Residuals"
  ) +
  theme_minimal()

# Print the plot
print(residual_plot_poly)
ggsave("residual_plot_poly.png", plot=residual_plot_poly, width=10, height=8, dpi=300)
```
```{r}
#Model with all the possible two-way interaction terms
model_full_interaction <- lm(concrete_compressive_strength ~ (cement+blast_furnace_slag+ fly_ash+water+superplasticizer+coarse_aggregate+fine_aggregate+age)^2, data = data)
summary(model_full_interaction)
```

```{r}
#Model with selected interaction terms 
selected_model_with_interactions <- lm(concrete_compressive_strength ~ cement+blast_furnace_slag+fly_ash+water+superplasticizer+                                                                    coarse_aggregate+fine_aggregate+age+
                                         blast_furnace_slag:fine_aggregate+
                                         blast_furnace_slag:fly_ash+
                                         water:coarse_aggregate+
                                         blast_furnace_slag:age+
                                         fly_ash:fine_aggregate+
                                         fly_ash:age
                                         ,data=data)
print(BIC(selected_model_with_interactions))
print(ols_mallows_cp(selected_model_with_interactions,model_full_linear))
summary(selected_model_with_interactions)
```
```{r}
#Residual plot of interaction model
residuals_data <- data.frame(
  Residuals = residuals(selected_model_with_interactions),
  Fitted = fitted(selected_model_with_interactions)
)

library(ggplot2)
residual_plot_interaction <- ggplot(residuals_data, aes(x=Fitted, y=Residuals)) +
  geom_point(colour="green") +
  geom_hline(yintercept=0, colour="red") +
  labs(
    x="Fitted Values",
    y="Residuals"
  ) +
  theme_minimal()

# Print the plot
print(residual_plot_interaction)
ggsave("residual_plot_interaction.png", plot=residual_plot_interaction, width=10, height=8, dpi=300)
```

```{r}
#cross validation for each model 
library(caret)
set.seed(123)
train.control <- trainControl(method = "cv", 
                              number = 5)
model_cv_full_linear <- train(concrete_compressive_strength~., 
data = data, method = "lm", trControl = train.control)
rmse_full_linear <- model_cv_full_linear$results$RMSE

model_cv_poly <- train(concrete_compressive_strength ~ cement + blast_furnace_slag + fly_ash + water + poly(superplasticizer,2) + coarse_aggregate + fine_aggregate + poly(age,2), 
data = data, method = "lm", trControl = train.control)
rmse_poly <- model_cv_poly$results$RMSE

model_cv_interaction <- train(concrete_compressive_strength ~ cement+blast_furnace_slag+fly_ash+water+superplasticizer+                                                                    coarse_aggregate+fine_aggregate+age+
                                         blast_furnace_slag:fine_aggregate+
                                         blast_furnace_slag:fly_ash+
                                         water:coarse_aggregate+
                                         blast_furnace_slag:age+
                                         fly_ash:fine_aggregate+
                                         fly_ash:age, 
data = data, method = "lm", trControl = train.control)
rmse_interaction <- model_cv_interaction$results$RMSE

#RMSE values for each model
print(rmse_full_linear)
print(rmse_poly)
print(rmse_interaction)
```



